# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'chirpy' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'BDBOAuth1Manager', '1.4'
  pod 'AFNetworking', '2.4.1'
  pod 'MBProgressHUD'
  # Pods for chirpy

end