# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'chirpy' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'BDBOAuth1Manager'
  pod 'AFNetworking', '~>2.6'
  pod 'MBProgressHUD'
  # Pods for chirpy

end
